services:

  postgres:
    image: postgres:17-alpine
    container_name: payguard-postgres

    environment:
      POSTGRES_DB: payguard
      POSTGRES_USER: payguard
      POSTGRES_PASSWORD: payguard

    ports:
      - "5432:5432"

    volumes:
      - payguard-postgres-data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U payguard -d payguard"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  payguard-postgres-data: