{
 "title": "PayGuard - Logs & Incident Investigation",
 "tags": [
  "payguard",
  "sre",
  "loki",
  "logs"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "service", "label": "Service", "query": "label_values(service)" }
  ]
 },
 "panels": [
  {
   "title": "Live Service Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{service=\"$service\"}"
    }
   ]
  },
  {
   "title": "Errors / Exceptions / Failures",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{service=\"$service\"} |~ \"(?i)error|exception|failed|failure\""
    }
   ]
  },
  {
   "title": "Payment Reconciliation Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "{service=\"payment-service\"} |~ \"(?i)reconcil\""
    }
   ]
  },
  {
   "title": "Payment Provider Activity",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "{service=\"payment-service\"} |~ \"(?i)provider\""
    }
   ]
  },
  {
   "title": "Log Volume by Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "logs" } },
   "targets": [
    {
     "expr": "sum by (service) (count_over_time({service=~\".+\"}[1m]))",
     "legendFormat": "{{service}}"
    }
   ]
  }
 ]
}