apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: payguard
spec:
  selector:
    app: payment-service

  ports:
    - name: http
      port: 8081
      targetPort: 8081
      nodePort: 30081

  type: NodePort
