const steps = [
  {title:'Client sends payment',state:'NEW REQUEST',description:'The client POSTs a payment with an Idempotency-Key. That key identifies this logical payment across retries.',lesson:'The key belongs to the payment attempt, not to a single HTTP connection.',code:'POST /api/v1/payments\nIdempotency-Key: DEMO-TIMEOUT-...\n{ "customerId": "CUSTOMER-DEMO", "amount": 149900, "currency": "INR" }'},
  {title:'Provider charges, then times out',state:'RESPONSE LOST',description:'The fake provider records SUCCESS, but throws a timeout before the API receives confirmation.',lesson:'A network timeout cannot prove a decline. Retrying a charge without checking its earlier outcome is unsafe.',code:'provider_timeout_after_success\nProvider record: SUCCESS\nAPI response from provider: timeout'},
  {title:'API preserves uncertainty',state:'UNKNOWN',description:'PayGuard records UNKNOWN in PostgreSQL and schedules a status check rather than reporting FAILED.',lesson:'Durable state lets the reconciliation worker continue after a request or process ends.',code:'Payment status: UNKNOWN\nnextReconciliationAt: scheduled\nIdempotency-Key: unchanged'},
  {title:'Client retries the same key',state:'SAME PAYMENT ID',description:'The repeated POST returns the existing payment. It does not create another payment record.',lesson:'The hosted demo asserts that original and retry IDs match.',code:'POST /api/v1/payments\nIdempotency-Key: DEMO-TIMEOUT-...\nRetry payment ID == original payment ID'},
  {title:'Worker verifies provider status',state:'SUCCESS',description:'The background worker queries the provider, sees its stored SUCCESS, and updates the original payment.',lesson:'UNKNOWN → SUCCESS resolves uncertainty without a second charge. Monitoring exposes recovery signals.',code:'Provider status lookup: SUCCESS\nPayment status: UNKNOWN → SUCCESS\nReconciliation: complete'}
];
const buttons = [...document.querySelectorAll('[data-step]')];
function showStep(index){const step=steps[index];if(!step)return;document.getElementById('step-title').textContent=step.title;document.getElementById('step-description').textContent=step.description;document.getElementById('step-lesson').textContent=step.lesson;document.getElementById('state-value').textContent=step.state;document.getElementById('step-code').textContent=step.code;for(const button of buttons)button.setAttribute('aria-pressed',String(Number(button.dataset.step)===index));}
for(const button of buttons)button.addEventListener('click',()=>showStep(Number(button.dataset.step)));
